In [1]:
import sys
print(sys.version)

3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nba_api.stats.endpoints import leaguegamefinder

print("pandas:", pd.__version__)
print("numpy:", np.__version__)
print("matplotlib:", plt.matplotlib.__version__)
print("seaborn:", sns.__version__)
print("All libraries loaded successfully!")

pandas: 3.0.3
numpy: 1.26.4
matplotlib: 3.7.0
seaborn: 0.13.2
All libraries loaded successfully!

In [4]:
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams
import time

nba_teams = teams.get_teams()
heat = [team for team in nba_teams if team['abbreviation'] == 'MIA'][0]
thunder = [team for team in nba_teams if team['abbreviation'] == 'OKC'][0]

print("Heat team info:", heat)
print("Thunder team info:", thunder)

Heat team info: {'id': 1610612748, 'full_name': 'Miami Heat', 'abbreviation': 'MIA', 'nickname': 'Heat', 'city': 'Miami', 'state': 'Florida', 'year_founded': 1988}
Thunder team info: {'id': 1610612760, 'full_name': 'Oklahoma City Thunder', 'abbreviation': 'OKC', 'nickname': 'Thunder', 'city': 'Oklahoma City', 'state': 'Oklahoma', 'year_founded': 1967}

In [5]:
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=heat['id'], season_nullable='2011-12', season_type_nullable='Playoffs')

heat_playoffs = gamefinder.get_data_frames()[0]

print("Shape", heat_playoffs.shape)
print("\nColumns:", heat_playoffs.columns)
print("\nAll Heat playoff games:")
heat_playoffs

Shape (23, 28)

Columns: Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'PTS', 'FGM', 'FGA', 'FG_PCT',
       'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB',
       'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PLUS_MINUS'],
      dtype='str')

All Heat playoff games:

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42011,1610612748,MIA,Miami Heat,0041100405,2012-06-21,MIA vs. OKC,W,241,121,...,0.818,8,33,41,25,8,7,13,21,15.0
1,42011,1610612748,MIA,Miami Heat,0041100404,2012-06-19,MIA vs. OKC,W,239,104,...,0.720,9,31,40,19,8,2,9,18,6.0
2,42011,1610612748,MIA,Miami Heat,0041100403,2012-06-17,MIA vs. OKC,W,240,91,...,0.886,14,31,45,13,6,5,12,19,6.0
3,42011,1610612748,MIA,Miami Heat,0041100402,2012-06-14,MIA @ OKC,W,238,100,...,0.880,11,29,40,13,5,4,13,21,4.0
4,42011,1610612748,MIA,Miami Heat,0041100401,2012-06-12,MIA @ OKC,L,240,94,...,0.778,7,28,35,20,6,1,10,19,-11.0
5,42011,1610612748,MIA,Miami Heat,0041100307,2012-06-09,MIA vs. BOS,W,240,101,...,0.741,9,29,38,16,8,3,13,14,13.0
6,42011,1610612748,MIA,Miami Heat,0041100306,2012-06-07,MIA @ BOS,W,241,98,...,0.773,10,34,44,15,8,4,12,21,19.0
7,42011,1610612748,MIA,Miami Heat,0041100305,2012-06-05,MIA vs. BOS,L,239,90,...,0.760,12,37,49,13,6,3,15,21,-4.0
8,42011,1610612748,MIA,Miami Heat,0041100304,2012-06-03,MIA @ BOS,L,265,91,...,0.708,7,33,40,20,6,6,17,28,-2.0
9,42011,1610612748,MIA,Miami Heat,0041100303,2012-06-01,MIA @ BOS,L,241,91,...,0.500,6,26,32,20,5,5,10,24,-10.0
10,42011,1610612748,MIA,Miami Heat,0041100302,2012-05-30,MIA vs. BOS,W,266,115,...,0.660,13,29,42,24,7,5,8,18,4.0
11,42011,1610612748,MIA,Miami Heat,0041100301,2012-05-28,MIA vs. BOS,W,240,93,...,0.696,13,35,48,17,4,11,12,21,14.0
12,42011,1610612748,MIA,Miami Heat,0041100206,2012-05-24,MIA @ IND,W,240,105,...,0.800,5,21,26,16,9,4,9,20,12.0
13,42011,1610612748,MIA,Miami Heat,0041100205,2012-05-22,MIA vs. IND,W,239,115,...,0.690,7,42,49,20,5,10,13,20,32.0
14,42011,1610612748,MIA,Miami Heat,0041100204,2012-05-20,MIA @ IND,W,239,101,...,0.714,14,33,47,20,8,9,15,24,8.0
15,42011,1610612748,MIA,Miami Heat,0041100203,2012-05-17,MIA @ IND,L,240,75,...,0.722,11,25,36,9,5,6,14,21,-19.0
16,42011,1610612748,MIA,Miami Heat,0041100202,2012-05-15,MIA vs. IND,L,240,75,...,0.690,14,26,40,11,10,5,12,22,-3.0
17,42011,1610612748,MIA,Miami Heat,0041100201,2012-05-13,MIA vs. IND,W,239,95,...,0.763,15,30,45,16,8,5,12,22,9.0
18,42011,1610612748,MIA,Miami Heat,0041100115,2012-05-09,MIA vs. NYK,W,241,106,...,0.853,13,29,42,20,7,3,10,18,12.0
19,42011,1610612748,MIA,Miami Heat,0041100114,2012-05-06,MIA @ NYK,L,240,87,...,0.686,9,31,40,20,8,6,14,26,-2.0
20,42011,1610612748,MIA,Miami Heat,0041100113,2012-05-03,MIA @ NYK,W,242,87,...,0.818,7,33,40,11,13,3,17,21,17.0
21,42011,1610612748,MIA,Miami Heat,0041100112,2012-04-30,MIA vs. NYK,W,240,104,...,0.704,7,26,33,28,6,3,8,17,10.0
22,42011,1610612748,MIA,Miami Heat,0041100111,2012-04-28,MIA vs. NYK,W,239,100,...,0.727,13,25,38,16,12,4,14,17,33.0

In [6]:
heat_playoffs.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42011,1610612748,MIA,Miami Heat,0041100405,2012-06-21,MIA vs. OKC,W,241,121,...,0.818,8,33,41,25,8,7,13,21,15.0
1,42011,1610612748,MIA,Miami Heat,0041100404,2012-06-19,MIA vs. OKC,W,239,104,...,0.720,9,31,40,19,8,2,9,18,6.0
2,42011,1610612748,MIA,Miami Heat,0041100403,2012-06-17,MIA vs. OKC,W,240,91,...,0.886,14,31,45,13,6,5,12,19,6.0
3,42011,1610612748,MIA,Miami Heat,0041100402,2012-06-14,MIA @ OKC,W,238,100,...,0.880,11,29,40,13,5,4,13,21,4.0
4,42011,1610612748,MIA,Miami Heat,0041100401,2012-06-12,MIA @ OKC,L,240,94,...,0.778,7,28,35,20,6,1,10,19,-11.0

In [10]:
finals_games = heat_playoffs[heat_playoffs['GAME_ID'].str.contains('0411004')]
finals_games[['GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL']]

      GAME_ID   GAME_DATE      MATCHUP WL
0  0041100405  2012-06-21  MIA vs. OKC  W
1  0041100404  2012-06-19  MIA vs. OKC  W
2  0041100403  2012-06-17  MIA vs. OKC  W
3  0041100402  2012-06-14    MIA @ OKC  W
4  0041100401  2012-06-12    MIA @ OKC  L